name: Owens Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: publish
        run: dotnet publish --no-build --no-restore -o ./dist

      - name: deploy
        uses: azure/webapps-deploy@v3
        with:
          package: "./dist"
          app-name: "asc-owens-app-dev"
          publish-profile: ${{ secrets.owens_dev }}